# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81dda03a17c62156e85e77b7c7b9ebb22acba220d098582efb2bd491a7c637b629318e846fdfcc5c327b531e48c6827decbbff311b9480fe69ccb155e6cdfe53

test:
  secret_key_base: 03f22a6f353f682da616089945e05d47f60b4f0d2236df0e99084c3506585c647621f031182b08092415dd4712b2fd49fae2f0d79b54d8d0849acc209201465c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
